rg_name = "azure-stack"
rg_location = "Central India"
vnetcidr = "172.16.0.0/16"
websubnetcidr = "172.16.1.0/24"
appsubnetcidr = "172.16.2.0/24"
dbsubnetcidr = "172.16.3.0/24"
web_host_name = "webserver"
web_user_name = "user_web"
web_os_password = "@WebUser1"
app_host_name = "appserver"
app_user_name = "user_app"
app_os_password = "@AppUser1"
primary_database = "primary-db"
primary_database_admin = "admin"
primary_database_password = "P@SSw0rd"
primary_database_version = "12.0"

